//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace WebService.WSUpdateSobject {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSUpdateSObjectsBinding", Namespace="http://soap.sforce.com/schemas/class/WSUpdateSObjects")]
    public partial class WSUpdateSObjectsService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private SessionHeader sessionHeaderValueField;
        
        private CallOptions callOptionsValueField;
        
        private DebuggingHeader debuggingHeaderValueField;
        
        private AllowFieldTruncationHeader allowFieldTruncationHeaderValueField;
        
        private DebuggingInfo debuggingInfoValueField;
        
        private System.Threading.SendOrPostCallback UpdtCntctNLnOpprtntyDetailOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSUpdateSObjectsService() {
            this.Url = global::WebService.Properties.Settings.Default.WebService_WSUpdateSobject_WSUpdateSObjectsService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public SessionHeader SessionHeaderValue {
            get {
                return this.sessionHeaderValueField;
            }
            set {
                this.sessionHeaderValueField = value;
            }
        }
        
        public CallOptions CallOptionsValue {
            get {
                return this.callOptionsValueField;
            }
            set {
                this.callOptionsValueField = value;
            }
        }
        
        public DebuggingHeader DebuggingHeaderValue {
            get {
                return this.debuggingHeaderValueField;
            }
            set {
                this.debuggingHeaderValueField = value;
            }
        }
        
        public AllowFieldTruncationHeader AllowFieldTruncationHeaderValue {
            get {
                return this.allowFieldTruncationHeaderValueField;
            }
            set {
                this.allowFieldTruncationHeaderValueField = value;
            }
        }
        
        public DebuggingInfo DebuggingInfoValue {
            get {
                return this.debuggingInfoValueField;
            }
            set {
                this.debuggingInfoValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UpdtCntctNLnOpprtntyDetailCompletedEventHandler UpdtCntctNLnOpprtntyDetailCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CallOptionsValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("AllowFieldTruncationHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("DebuggingInfoValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("DebuggingHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://soap.sforce.com/schemas/class/WSUpdateSObjects", ResponseNamespace="http://soap.sforce.com/schemas/class/WSUpdateSObjects", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result", IsNullable=true)]
        public Error[] UpdtCntctNLnOpprtntyDetail([System.Xml.Serialization.XmlElementAttribute("lstLnOppDetail", IsNullable=true)] LoanOpprtntyDetail[] lstLnOppDetail, [System.Xml.Serialization.XmlElementAttribute("lstContactDetail", IsNullable=true)] ContactDetail[] lstContactDetail) {
            object[] results = this.Invoke("UpdtCntctNLnOpprtntyDetail", new object[] {
                        lstLnOppDetail,
                        lstContactDetail});
            return ((Error[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdtCntctNLnOpprtntyDetailAsync(LoanOpprtntyDetail[] lstLnOppDetail, ContactDetail[] lstContactDetail) {
            this.UpdtCntctNLnOpprtntyDetailAsync(lstLnOppDetail, lstContactDetail, null);
        }
        
        /// <remarks/>
        public void UpdtCntctNLnOpprtntyDetailAsync(LoanOpprtntyDetail[] lstLnOppDetail, ContactDetail[] lstContactDetail, object userState) {
            if ((this.UpdtCntctNLnOpprtntyDetailOperationCompleted == null)) {
                this.UpdtCntctNLnOpprtntyDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdtCntctNLnOpprtntyDetailOperationCompleted);
            }
            this.InvokeAsync("UpdtCntctNLnOpprtntyDetail", new object[] {
                        lstLnOppDetail,
                        lstContactDetail}, this.UpdtCntctNLnOpprtntyDetailOperationCompleted, userState);
        }
        
        private void OnUpdtCntctNLnOpprtntyDetailOperationCompleted(object arg) {
            if ((this.UpdtCntctNLnOpprtntyDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdtCntctNLnOpprtntyDetailCompleted(this, new UpdtCntctNLnOpprtntyDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.sforce.com/schemas/class/WSUpdateSObjects")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://soap.sforce.com/schemas/class/WSUpdateSObjects", IsNullable=false)]
    public partial class CallOptions : System.Web.Services.Protocols.SoapHeader {
        
        private string clientField;
        
        /// <remarks/>
        public string client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.sforce.com/schemas/class/WSUpdateSObjects")]
    public partial class Error {
        
        private string errorMessageField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.sforce.com/schemas/class/WSCntctNLnOpprtntyDetail")]
    public partial class ContactDetail {
        
        private string birthdateField;
        
        private string birthdateCoBorrowerField;
        
        private string borrowerFirstNameField;
        
        private string borrowerLastNameField;
        
        private string contactIDField;
        
        private string emailField;
        
        private string emailCoBorrowerField;
        
        private string employerAddressField;
        
        private string employerAddressCoBorrowerField;
        
        private string employerCityField;
        
        private string employerCityCoBorrowerField;
        
        private string employerNameField;
        
        private string employerNameCoBorrowerField;
        
        private string firstNameCoBorrowerField;
        
        private string homePhoneField;
        
        private string incomeField;
        
        private string incomeCoBorrowerField;
        
        private string jobTitleField;
        
        private string jobTitleCoBorrowerField;
        
        private string lastNameCoborrowerField;
        
        private string mailingCityField;
        
        private string mailingPostalCodeField;
        
        private string mailingStateField;
        
        private string mailingStreetField;
        
        private string maritalStatusField;
        
        private string middleCreditScoreBorrowerField;
        
        private string mobileCoBorrowerField;
        
        private string mobilePhoneField;
        
        private string sSNField;
        
        private string sSNCoBorrowerField;
        
        private string workPhoneCoBorrowerField;
        
        private string yearsInLineOfWorkField;
        
        private string yearsInLineOfWorkCoBorrowerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Birthdate {
            get {
                return this.birthdateField;
            }
            set {
                this.birthdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BirthdateCoBorrower {
            get {
                return this.birthdateCoBorrowerField;
            }
            set {
                this.birthdateCoBorrowerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BorrowerFirstName {
            get {
                return this.borrowerFirstNameField;
            }
            set {
                this.borrowerFirstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BorrowerLastName {
            get {
                return this.borrowerLastNameField;
            }
            set {
                this.borrowerLastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ContactID {
            get {
                return this.contactIDField;
            }
            set {
                this.contactIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EmailCoBorrower {
            get {
                return this.emailCoBorrowerField;
            }
            set {
                this.emailCoBorrowerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EmployerAddress {
            get {
                return this.employerAddressField;
            }
            set {
                this.employerAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EmployerAddressCoBorrower {
            get {
                return this.employerAddressCoBorrowerField;
            }
            set {
                this.employerAddressCoBorrowerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EmployerCity {
            get {
                return this.employerCityField;
            }
            set {
                this.employerCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EmployerCityCoBorrower {
            get {
                return this.employerCityCoBorrowerField;
            }
            set {
                this.employerCityCoBorrowerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EmployerName {
            get {
                return this.employerNameField;
            }
            set {
                this.employerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EmployerNameCoBorrower {
            get {
                return this.employerNameCoBorrowerField;
            }
            set {
                this.employerNameCoBorrowerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FirstNameCoBorrower {
            get {
                return this.firstNameCoBorrowerField;
            }
            set {
                this.firstNameCoBorrowerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string HomePhone {
            get {
                return this.homePhoneField;
            }
            set {
                this.homePhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Income {
            get {
                return this.incomeField;
            }
            set {
                this.incomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IncomeCoBorrower {
            get {
                return this.incomeCoBorrowerField;
            }
            set {
                this.incomeCoBorrowerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string JobTitle {
            get {
                return this.jobTitleField;
            }
            set {
                this.jobTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string JobTitleCoBorrower {
            get {
                return this.jobTitleCoBorrowerField;
            }
            set {
                this.jobTitleCoBorrowerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LastNameCoborrower {
            get {
                return this.lastNameCoborrowerField;
            }
            set {
                this.lastNameCoborrowerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MailingCity {
            get {
                return this.mailingCityField;
            }
            set {
                this.mailingCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MailingPostalCode {
            get {
                return this.mailingPostalCodeField;
            }
            set {
                this.mailingPostalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MailingState {
            get {
                return this.mailingStateField;
            }
            set {
                this.mailingStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MailingStreet {
            get {
                return this.mailingStreetField;
            }
            set {
                this.mailingStreetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MaritalStatus {
            get {
                return this.maritalStatusField;
            }
            set {
                this.maritalStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MiddleCreditScoreBorrower {
            get {
                return this.middleCreditScoreBorrowerField;
            }
            set {
                this.middleCreditScoreBorrowerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MobileCoBorrower {
            get {
                return this.mobileCoBorrowerField;
            }
            set {
                this.mobileCoBorrowerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MobilePhone {
            get {
                return this.mobilePhoneField;
            }
            set {
                this.mobilePhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SSN {
            get {
                return this.sSNField;
            }
            set {
                this.sSNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SSNCoBorrower {
            get {
                return this.sSNCoBorrowerField;
            }
            set {
                this.sSNCoBorrowerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string WorkPhoneCoBorrower {
            get {
                return this.workPhoneCoBorrowerField;
            }
            set {
                this.workPhoneCoBorrowerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string YearsInLineOfWork {
            get {
                return this.yearsInLineOfWorkField;
            }
            set {
                this.yearsInLineOfWorkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string YearsInLineOfWorkCoBorrower {
            get {
                return this.yearsInLineOfWorkCoBorrowerField;
            }
            set {
                this.yearsInLineOfWorkCoBorrowerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.sforce.com/schemas/class/WSCntctNLnOpprtntyDetail")]
    public partial class LoanOpprtntyDetail {
        
        private string appraisalDueDateField;
        
        private string appraisalOrderedField;
        
        private string appraisalReceivedField;
        
        private string appraisedValueField;
        
        private string appraiserField;
        
        private string cashToCloseField;
        
        private string cLTVField;
        
        private string countyField;
        
        private string discountField;
        
        private string docsRequestedDateField;
        
        private string downPaymentField;
        
        private string escrowAgentField;
        
        private string finalGFEDateField;
        
        private string firstPaymentDateField;
        
        private string gFEExpirationDateField;
        
        private string hazardInsuranceField;
        
        private string hOAField;
        
        private string indexField;
        
        private string insuranceAgentField;
        
        private string insuranceReceivedField;
        
        private string insuranceReceiveDateField;
        
        private string insuranceRequestedDateField;
        
        private string lenderField;
        
        private string lenderCreditField;
        
        private string loanAmountField;
        
        private string loanIDField;
        
        private string loanProgramField;
        
        private string loanPurposeField;
        
        private string loanTypeField;
        
        private string lockDateField;
        
        private string lockExperationDateField;
        
        private string lTVField;
        
        private string marginField;
        
        private string monthlyPaymentField;
        
        private string mortgageInsuranceField;
        
        private string occupancyField;
        
        private string opportunityIDField;
        
        private string processorField;
        
        private string propertyAddressField;
        
        private string propertyCityField;
        
        private string propertyOriginalCostField;
        
        private string propertyPostalCodeField;
        
        private string propertyStateField;
        
        private string propertyTaxField;
        
        private string propertyTypeField;
        
        private string proposedMonthlyPaymentField;
        
        private string proposedTotalExpensesField;
        
        private string purchasePriceField;
        
        private string qcField;
        
        private string rateField;
        
        private string realtorField;
        
        private string realtorBuyingAgentField;
        
        private string requiredCompField;
        
        private string sentToQCField;
        
        private string titleAgentField;
        
        private string titleReceivedField;
        
        private string titleRequestedField;
        
        private string transcriptsReceivedDateField;
        
        private string transcriptsRequestedDateField;
        
        private string underwriterField;
        
        private string vestingBorrowerField;
        
        private string vestingCoBorrowerField;
        
        private string vestingNotesField;
        
        private string vOEReceivedBorrowerField;
        
        private string vOEReceivedCoBorrowerField;
        
        private string vOERequestBorrowerField;
        
        private string vOERequestCoBorrowerField;
        
        private string yearPropertyAcquiredField;
        
        private string yieldSpreadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AppraisalDueDate {
            get {
                return this.appraisalDueDateField;
            }
            set {
                this.appraisalDueDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AppraisalOrdered {
            get {
                return this.appraisalOrderedField;
            }
            set {
                this.appraisalOrderedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AppraisalReceived {
            get {
                return this.appraisalReceivedField;
            }
            set {
                this.appraisalReceivedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AppraisedValue {
            get {
                return this.appraisedValueField;
            }
            set {
                this.appraisedValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Appraiser {
            get {
                return this.appraiserField;
            }
            set {
                this.appraiserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CashToClose {
            get {
                return this.cashToCloseField;
            }
            set {
                this.cashToCloseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CLTV {
            get {
                return this.cLTVField;
            }
            set {
                this.cLTVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string County {
            get {
                return this.countyField;
            }
            set {
                this.countyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Discount {
            get {
                return this.discountField;
            }
            set {
                this.discountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DocsRequestedDate {
            get {
                return this.docsRequestedDateField;
            }
            set {
                this.docsRequestedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DownPayment {
            get {
                return this.downPaymentField;
            }
            set {
                this.downPaymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EscrowAgent {
            get {
                return this.escrowAgentField;
            }
            set {
                this.escrowAgentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FinalGFEDate {
            get {
                return this.finalGFEDateField;
            }
            set {
                this.finalGFEDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FirstPaymentDate {
            get {
                return this.firstPaymentDateField;
            }
            set {
                this.firstPaymentDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GFEExpirationDate {
            get {
                return this.gFEExpirationDateField;
            }
            set {
                this.gFEExpirationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string HazardInsurance {
            get {
                return this.hazardInsuranceField;
            }
            set {
                this.hazardInsuranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string HOA {
            get {
                return this.hOAField;
            }
            set {
                this.hOAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string InsuranceAgent {
            get {
                return this.insuranceAgentField;
            }
            set {
                this.insuranceAgentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string InsuranceReceived {
            get {
                return this.insuranceReceivedField;
            }
            set {
                this.insuranceReceivedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string InsuranceReceiveDate {
            get {
                return this.insuranceReceiveDateField;
            }
            set {
                this.insuranceReceiveDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string InsuranceRequestedDate {
            get {
                return this.insuranceRequestedDateField;
            }
            set {
                this.insuranceRequestedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Lender {
            get {
                return this.lenderField;
            }
            set {
                this.lenderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LenderCredit {
            get {
                return this.lenderCreditField;
            }
            set {
                this.lenderCreditField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LoanAmount {
            get {
                return this.loanAmountField;
            }
            set {
                this.loanAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LoanID {
            get {
                return this.loanIDField;
            }
            set {
                this.loanIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LoanProgram {
            get {
                return this.loanProgramField;
            }
            set {
                this.loanProgramField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LoanPurpose {
            get {
                return this.loanPurposeField;
            }
            set {
                this.loanPurposeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LoanType {
            get {
                return this.loanTypeField;
            }
            set {
                this.loanTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LockDate {
            get {
                return this.lockDateField;
            }
            set {
                this.lockDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LockExperationDate {
            get {
                return this.lockExperationDateField;
            }
            set {
                this.lockExperationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LTV {
            get {
                return this.lTVField;
            }
            set {
                this.lTVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Margin {
            get {
                return this.marginField;
            }
            set {
                this.marginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MonthlyPayment {
            get {
                return this.monthlyPaymentField;
            }
            set {
                this.monthlyPaymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MortgageInsurance {
            get {
                return this.mortgageInsuranceField;
            }
            set {
                this.mortgageInsuranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Occupancy {
            get {
                return this.occupancyField;
            }
            set {
                this.occupancyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OpportunityID {
            get {
                return this.opportunityIDField;
            }
            set {
                this.opportunityIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Processor {
            get {
                return this.processorField;
            }
            set {
                this.processorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PropertyAddress {
            get {
                return this.propertyAddressField;
            }
            set {
                this.propertyAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PropertyCity {
            get {
                return this.propertyCityField;
            }
            set {
                this.propertyCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PropertyOriginalCost {
            get {
                return this.propertyOriginalCostField;
            }
            set {
                this.propertyOriginalCostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PropertyPostalCode {
            get {
                return this.propertyPostalCodeField;
            }
            set {
                this.propertyPostalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PropertyState {
            get {
                return this.propertyStateField;
            }
            set {
                this.propertyStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PropertyTax {
            get {
                return this.propertyTaxField;
            }
            set {
                this.propertyTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PropertyType {
            get {
                return this.propertyTypeField;
            }
            set {
                this.propertyTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProposedMonthlyPayment {
            get {
                return this.proposedMonthlyPaymentField;
            }
            set {
                this.proposedMonthlyPaymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProposedTotalExpenses {
            get {
                return this.proposedTotalExpensesField;
            }
            set {
                this.proposedTotalExpensesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PurchasePrice {
            get {
                return this.purchasePriceField;
            }
            set {
                this.purchasePriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string QC {
            get {
                return this.qcField;
            }
            set {
                this.qcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Realtor {
            get {
                return this.realtorField;
            }
            set {
                this.realtorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RealtorBuyingAgent {
            get {
                return this.realtorBuyingAgentField;
            }
            set {
                this.realtorBuyingAgentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RequiredComp {
            get {
                return this.requiredCompField;
            }
            set {
                this.requiredCompField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SentToQC {
            get {
                return this.sentToQCField;
            }
            set {
                this.sentToQCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TitleAgent {
            get {
                return this.titleAgentField;
            }
            set {
                this.titleAgentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TitleReceived {
            get {
                return this.titleReceivedField;
            }
            set {
                this.titleReceivedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TitleRequested {
            get {
                return this.titleRequestedField;
            }
            set {
                this.titleRequestedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TranscriptsReceivedDate {
            get {
                return this.transcriptsReceivedDateField;
            }
            set {
                this.transcriptsReceivedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TranscriptsRequestedDate {
            get {
                return this.transcriptsRequestedDateField;
            }
            set {
                this.transcriptsRequestedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Underwriter {
            get {
                return this.underwriterField;
            }
            set {
                this.underwriterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string VestingBorrower {
            get {
                return this.vestingBorrowerField;
            }
            set {
                this.vestingBorrowerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string VestingCoBorrower {
            get {
                return this.vestingCoBorrowerField;
            }
            set {
                this.vestingCoBorrowerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string VestingNotes {
            get {
                return this.vestingNotesField;
            }
            set {
                this.vestingNotesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string VOEReceivedBorrower {
            get {
                return this.vOEReceivedBorrowerField;
            }
            set {
                this.vOEReceivedBorrowerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string VOEReceivedCoBorrower {
            get {
                return this.vOEReceivedCoBorrowerField;
            }
            set {
                this.vOEReceivedCoBorrowerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string VOERequestBorrower {
            get {
                return this.vOERequestBorrowerField;
            }
            set {
                this.vOERequestBorrowerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string VOERequestCoBorrower {
            get {
                return this.vOERequestCoBorrowerField;
            }
            set {
                this.vOERequestCoBorrowerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string YearPropertyAcquired {
            get {
                return this.yearPropertyAcquiredField;
            }
            set {
                this.yearPropertyAcquiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string YieldSpread {
            get {
                return this.yieldSpreadField;
            }
            set {
                this.yieldSpreadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.sforce.com/schemas/class/WSUpdateSObjects")]
    public partial class LogInfo {
        
        private LogCategory categoryField;
        
        private LogCategoryLevel levelField;
        
        /// <remarks/>
        public LogCategory category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public LogCategoryLevel level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.sforce.com/schemas/class/WSUpdateSObjects")]
    public enum LogCategory {
        
        /// <remarks/>
        Db,
        
        /// <remarks/>
        Workflow,
        
        /// <remarks/>
        Validation,
        
        /// <remarks/>
        Callout,
        
        /// <remarks/>
        Apex_code,
        
        /// <remarks/>
        Apex_profiling,
        
        /// <remarks/>
        Visualforce,
        
        /// <remarks/>
        System,
        
        /// <remarks/>
        All,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.sforce.com/schemas/class/WSUpdateSObjects")]
    public enum LogCategoryLevel {
        
        /// <remarks/>
        Internal,
        
        /// <remarks/>
        Finest,
        
        /// <remarks/>
        Finer,
        
        /// <remarks/>
        Fine,
        
        /// <remarks/>
        Debug,
        
        /// <remarks/>
        Info,
        
        /// <remarks/>
        Warn,
        
        /// <remarks/>
        Error,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.sforce.com/schemas/class/WSUpdateSObjects")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://soap.sforce.com/schemas/class/WSUpdateSObjects", IsNullable=false)]
    public partial class AllowFieldTruncationHeader : System.Web.Services.Protocols.SoapHeader {
        
        private bool allowFieldTruncationField;
        
        /// <remarks/>
        public bool allowFieldTruncation {
            get {
                return this.allowFieldTruncationField;
            }
            set {
                this.allowFieldTruncationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.sforce.com/schemas/class/WSUpdateSObjects")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://soap.sforce.com/schemas/class/WSUpdateSObjects", IsNullable=false)]
    public partial class DebuggingInfo : System.Web.Services.Protocols.SoapHeader {
        
        private string debugLogField;
        
        /// <remarks/>
        public string debugLog {
            get {
                return this.debugLogField;
            }
            set {
                this.debugLogField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.sforce.com/schemas/class/WSUpdateSObjects")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://soap.sforce.com/schemas/class/WSUpdateSObjects", IsNullable=false)]
    public partial class SessionHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string sessionIdField;
        
        /// <remarks/>
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.sforce.com/schemas/class/WSUpdateSObjects")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://soap.sforce.com/schemas/class/WSUpdateSObjects", IsNullable=false)]
    public partial class DebuggingHeader : System.Web.Services.Protocols.SoapHeader {
        
        private LogInfo[] categoriesField;
        
        private LogType debugLevelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("categories")]
        public LogInfo[] categories {
            get {
                return this.categoriesField;
            }
            set {
                this.categoriesField = value;
            }
        }
        
        /// <remarks/>
        public LogType debugLevel {
            get {
                return this.debugLevelField;
            }
            set {
                this.debugLevelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.sforce.com/schemas/class/WSUpdateSObjects")]
    public enum LogType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Debugonly,
        
        /// <remarks/>
        Db,
        
        /// <remarks/>
        Profiling,
        
        /// <remarks/>
        Callout,
        
        /// <remarks/>
        Detail,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpdtCntctNLnOpprtntyDetailCompletedEventHandler(object sender, UpdtCntctNLnOpprtntyDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdtCntctNLnOpprtntyDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdtCntctNLnOpprtntyDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Error[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Error[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591